// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlr6aLrr4OpZg_XSfJ1qt-zmyFLkDhO1k',
    appId: '1:1023199518654:web:5f8f24fd886803751c23ef',
    messagingSenderId: '1023199518654',
    projectId: 'baat-cheet-91',
    authDomain: 'baat-cheet-91.firebaseapp.com',
    storageBucket: 'baat-cheet-91.appspot.com',
    measurementId: 'G-Z2YPCH3XD4',
    databaseURL: 'https://baat-cheet-91-default-rtdb.asia-southeast1.firebasedatabase.app'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMCyigHFGgSNdf9MUjkN8zHcj-A1xQdic',
    appId: '1:1023199518654:android:43c603e6ec89ffd11c23ef',
    messagingSenderId: '1023199518654',
    projectId: 'baat-cheet-91',
    storageBucket: 'baat-cheet-91.appspot.com',
    databaseURL: 'https://baat-cheet-91-default-rtdb.asia-southeast1.firebasedatabase.app'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuU5Kh-nTXLujp9Az8ZrjlGeLN5j9CSSQ',
    appId: '1:1023199518654:ios:11671db04d49ee861c23ef',
    messagingSenderId: '1023199518654',
    projectId: 'baat-cheet-91',
    storageBucket: 'baat-cheet-91.appspot.com',
    iosBundleId: 'com.example.baatCheetApp',
    databaseURL: 'https://baat-cheet-91-default-rtdb.asia-southeast1.firebasedatabase.app'
  );
}
